// Code generated by hertz generator.

package ledger

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ledgercreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ledgerdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ledgerupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ledgerlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
