// Code generated by hertz generator.

package asr

import (
	"context"

	asr "github.com/XZ0730/runFzu/biz/model/asr"
	"github.com/XZ0730/runFzu/biz/pack"
	"github.com/XZ0730/runFzu/biz/service"
	"github.com/XZ0730/runFzu/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ASRtoText .
// @router /api/speech_recog [POST]
func ASRtoText(ctx context.Context, c *app.RequestContext) {
	var err error
	fh, err := c.FormFile("speech")
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(asr.ASRResponse)
	data, code, msg := service.NewASRService().ASRtoText(fh)
	pack.PackASRResponse(resp, code, msg, data)
	c.JSON(consts.StatusOK, resp)
}

// FileUpload .
// @router /api/file [POST]
func FileUpload(ctx context.Context, c *app.RequestContext) {
	var err error
	resp := new(asr.FileUploadResponse)
	fileform, err := c.MultipartForm()
	fhs := fileform.File["multipartFiles"]
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	token_byte := c.GetHeader("token")
	claim, _ := utils.CheckToken(string(token_byte))
	data, code, msg := service.NewASRService().FileUpload(claim.UserId, fhs)
	pack.PackFilesUrl(resp, code, msg, data)
	c.JSON(consts.StatusOK, resp)
}
