// Code generated by hertz generator.

package ledger

import (
	"context"
	"github.com/XZ0730/runFzu/biz/model/base"
	"github.com/XZ0730/runFzu/biz/pack"
	"github.com/XZ0730/runFzu/biz/service"
	"github.com/XZ0730/runFzu/pkg/errno"
	"github.com/XZ0730/runFzu/pkg/utils"

	ledger "github.com/XZ0730/runFzu/biz/model/ledger"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// LedgerCreate .
// @router /api/ledger [POST]
func LedgerCreate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ledger.LedgerModel
	resp := new(ledger.LedgerCreateResponse)
	baseResp := new(base.BaseResponse)

	token_byte := c.GetHeader("token")
	claim, _ := utils.CheckToken(string(token_byte))
	err = c.BindAndValidate(&req)

	req.UserId = claim.UserId

	if err != nil {
		pack.PackBase(baseResp, errno.ParamErrorCode, errno.ParamError.ErrorMsg)
		c.JSON(consts.StatusOK, resp)
		return
	}
	code, msg := service.NewLedgerService().CreateLedger(claim.UserId, &req)
	pack.PackLedgerCreate(resp, code, msg, req)
	c.JSON(consts.StatusOK, resp)
}
