// Code generated by hertz generator.

package goal

import (
	"context"

	"github.com/XZ0730/runFzu/biz/model/base"
	goal "github.com/XZ0730/runFzu/biz/model/goal"
	"github.com/XZ0730/runFzu/biz/pack"
	"github.com/XZ0730/runFzu/biz/service"
	"github.com/XZ0730/runFzu/pkg/errno"
	"github.com/XZ0730/runFzu/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GoalCreate .
// @router /api.goal [POST]
func GoalCreate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req goal.GoalCreateRequest
	resp := new(base.BaseResponse)
	token_byte := c.GetHeader("token")
	claim, _ := utils.CheckToken(string(token_byte))
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.PackBase(resp, errno.ParamErrorCode, errno.ParamError.ErrorMsg)
		c.JSON(consts.StatusOK, resp)
		return
	}
	code, msg := service.NewGoalService().CreateGoal(claim.UserId, &req)
	pack.PackBase(resp, code, msg)
	c.JSON(consts.StatusOK, resp)
}

// GoalListGet .
// @router /api/goal [GET]
func GoalListGet(ctx context.Context, c *app.RequestContext) {
	var err error
	var req goal.BaseRequest
	resp := new(goal.GoalListGetResponse)

	token_byte := c.GetHeader("token")
	claim, _ := utils.CheckToken(string(token_byte))
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	goal_list, code, msg := service.NewGoalService().GetGoals(claim.UserId)
	pack.PackGoallist(resp, code, msg, goal_list)
	c.JSON(consts.StatusOK, resp)
}
