// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	asr "github.com/XZ0730/runFzu/biz/router/asr"
	base "github.com/XZ0730/runFzu/biz/router/base"
	goal "github.com/XZ0730/runFzu/biz/router/goal"
	ledger "github.com/XZ0730/runFzu/biz/router/ledger"
	multiledger "github.com/XZ0730/runFzu/biz/router/multiledger"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	asr.Register(r)

	multiledger.Register(r)

	ledger.Register(r)

	goal.Register(r)

	base.Register(r)

}
