// Code generated by hertz generator.

package consumption

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ledgerbalanceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateconsumptionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consumptionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rangeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsumbyrangeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconsumptionbyrangeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconsumptionbydateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consumption0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinbyrangeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getoutbyrangeMw() []app.HandlerFunc {
	// your code...
	return nil
}
